### ISSUE TITLE
Integrate CI

### ISSUE THREAD

**Issue by rpgeeganage** [fatso83/mini-mocha#10]
I think it is better to integration CI tool such as `https://travis-ci.org/` or `http://appveyor.com`

**Comment by fatso83** [comment]
No need for that anymore, now that we have Github Hooks!

**Comment by fatso83** [comment]
Eh, I haven't actually _set up_ Github hooks/actions, though, so shouldn't this issue still be open? When I referenced "that", I meant Travis, etc. I still think a CI step would be nice.

**Comment by fatso83** [comment]
The tests broke sometime in the last few commits .... Adding a Github action to run the tests would have been nice now!

**Comment by fatso83** [comment]
I have signed up for the Github action beta, but maybe we could setup Circle CI or AppVeyor, as you propsosed?

**Comment by rpgeeganage** [comment]
I can look into Circle CI.

**Comment by rpgeeganage** [comment]
It seems I cannot add `mini-mocha` repo to add CiricleCI.

**Comment by fatso83** [comment]
https://circleci.com/gh/fatso83/mini-mocha/tree/master
